import os
import numpy as np
import pandas as pd
import torch
from lime.lime_text import LimeTextExplainer
from live_bert_inference import LiveBERTInference

class BertXAI:
    def __init__(self, inference_engine=None):
        if inference_engine is None:
            self.inference_engine = LiveBERTInference()
        else:
            self.inference_engine = inference_engine
            
        # LIME explainer for model-agnostic text attribution
        self.explainer = LimeTextExplainer(class_names=['Benign', 'Ransomware'])
        
    def _predict_proba(self, texts):
        """
        Wrapper function required by LIME. Takes a list of strings and returns 
        a numpy array of probabilities of shape (len(texts), num_classes).
        """
        if not self.inference_engine.is_loaded:
            # Fallback if model is not loaded (e.g. training in progress)
            # Return uniform probabilities to avoid crashing LIME
            return np.array([[0.5, 0.5] for _ in texts])
            
        # Tokenize batch
        inputs = self.inference_engine.tokenizer(
            texts, 
            padding="max_length", 
            truncation=True, 
            max_length=128, 
            return_tensors="pt"
        )
        inputs = {k: v.to(self.inference_engine.device) for k, v in inputs.items()}
        
        with torch.no_grad():
            outputs = self.inference_engine.model(**inputs)
            logits = outputs.logits.cpu().numpy()
            
        # Softmax for probabilities
        exp_logits = np.exp(logits)
        probs = exp_logits / np.sum(exp_logits, axis=1, keepdims=True)
        return probs

    
    def explain_text(self, text, num_features=5, num_samples=100):
        """
        Phase 5B LIME Explanation: Takes the pre-computed behavioral_text directly.
        Input: exact string generated by live_domain_converter.py
        Output: dict with top contributing words/phrases and probabilities.
        """
        if not self.inference_engine.is_loaded:
            return {
                "generated_text": text,
                "prediction": "UNKNOWN",
                "benign_probability": 0.0,
                "ransomware_probability": 0.0,
                "top_contributions": [],
                "error": "Model training in progress or directory not found."
            }
            
        baseline_probs = self._predict_proba([text])[0]
        pred_class = np.argmax(baseline_probs)
        
        exp = self.explainer.explain_instance(
            text, 
            self._predict_proba, 
            num_features=num_features, 
            num_samples=num_samples
        )
        
        contributions = exp.as_list(label=1)
        
        return {
            "generated_text": text,
            "prediction": "Ransomware" if pred_class == 1 else "Benign",
            "benign_probability": round(float(baseline_probs[0]), 4),
            "ransomware_probability": round(float(baseline_probs[1]), 4),
            "top_contributions": contributions,
            "disclaimer": "This represents model attribution/contribution, NOT causal proof."
        }

    def explain(self, row, num_features=5, num_samples=100):
        """
        Explain which behavioral words/phrases contribute most to the BERT prediction.
        This provides model attribution/contribution, NOT causal proof.
        """
        # Convert row to behavioral text
        text = self.inference_engine.convert_to_text(row)
        
        if not self.inference_engine.is_loaded:
            return {
                "generated_text": text,
                "prediction": "UNKNOWN",
                "benign_probability": 0.0,
                "ransomware_probability": 0.0,
                "top_contributions": [],
                "error": "Model training in progress or directory not found."
            }
            
        # Get baseline prediction
        baseline_probs = self._predict_proba([text])[0]
        pred_class = np.argmax(baseline_probs)
        
        # Run LIME text explanation
        exp = self.explainer.explain_instance(
            text, 
            self._predict_proba, 
            num_features=num_features, 
            num_samples=num_samples
        )
        
        # Extract features for the predicted class
        contributions = exp.as_list(label=1) # Get contributions towards 'Ransomware' class by default
        
        return {
            "generated_text": text,
            "prediction": "Ransomware" if pred_class == 1 else "Benign",
            "benign_probability": round(float(baseline_probs[0]), 4),
            "ransomware_probability": round(float(baseline_probs[1]), 4),
            "top_contributions": contributions,
            "disclaimer": "This represents model attribution/contribution, NOT causal proof."
        }

def offline_test():
    print("--- Common BERT XAI Offline Test ---")
    
    csv_path = '5_mlran_dataset/Phase5A_Live_Telemetry/phase5a_benign_telemetry.csv'
    if not os.path.exists(csv_path):
        print(f"[-] Test dataset missing: {csv_path}")
        return
        
    df = pd.read_csv(csv_path)
    test_row = df.iloc[0]
    
    print("\nInitializing BERT XAI...")
    xai_engine = BertXAI()
    
    print("\n[Running XAI Attribution]")
    result = xai_engine.explain(test_row, num_samples=20) # small num_samples for quick offline test
    
    print(f"\nGenerated Text: {result['generated_text']}")
    print(f"Prediction: {result['prediction']}")
    print(f"Benign Probability: {result['benign_probability']}")
    print(f"Ransomware Probability: {result['ransomware_probability']}")
    
    if "top_contributions" in result and result["top_contributions"]:
        print("\nTop Contributing Words/Phrases (Attribution towards Ransomware):")
        for word, weight in result['top_contributions']:
            print(f"  {word}: {weight:.4f}")
            
    if "disclaimer" in result:
        print(f"\nNOTE: {result['disclaimer']}")
        
    if "error" in result:
        print(f"\nERROR: {result['error']}")

if __name__ == "__main__":
    offline_test()
