import os
import json
import pandas as pd
import numpy as np
import torch
from transformers import BertTokenizer, BertForSequenceClassification

class LiveBERTInference:
    def __init__(self, model_dir="6_experiments/bert_common_behavior_model"):
        self.model_dir = model_dir
        self.device = torch.device("cpu")
        self.is_loaded = False
        self.model = None
        self.tokenizer = None
        
        if os.path.exists(self.model_dir) and os.path.exists(os.path.join(self.model_dir, "config.json")):
            try:
                self.tokenizer = BertTokenizer.from_pretrained(self.model_dir)
                self.model = BertForSequenceClassification.from_pretrained(self.model_dir)
                self.model.to(self.device)
                self.model.eval()
                self.is_loaded = True
                print(f"[+] Loaded trained Common BERT model from {self.model_dir}")
            except Exception as e:
                print(f"[-] Error loading model: {e}")
        else:
            print(f"[-] Model directory {self.model_dir} not found. Training is likely still in progress.")

    def convert_to_text(self, row):
        """
        Converts the live 21-feature numerical Windows telemetry vector into 
        the exact 11-feature common behavioral text expected by the Common BERT model.
        """
        sections = []
        
        # --- FILE SYSTEM ---
        fs_text = []
        if row.get('fs_02_modification_count', 0) > 0:
            fs_text.append(f"modified {int(row['fs_02_modification_count'])} files")
        if row.get('fs_06_executable_files_dropped', 0) > 0:
            fs_text.append(f"dropped {int(row['fs_06_executable_files_dropped'])} executable files")
        if fs_text:
            sections.append("File behavior: " + ", ".join(fs_text) + ".")
            
        # --- PROCESS ---
        pr_text = []
        if row.get('pr_01_child_process_count', 0) > 0:
            pr_text.append(f"spawned {int(row['pr_01_child_process_count'])} child processes")
        if row.get('pr_02_suspicious_child_count', 0) > 0:
            pr_text.append(f"spawned {int(row['pr_02_suspicious_child_count'])} suspicious processes")
        if pr_text:
            sections.append("Process behavior: " + ", ".join(pr_text) + ".")
            
        # --- REGISTRY ---
        rg_text = []
        if row.get('rg_01_registry_keys_created', 0) > 0:
            rg_text.append(f"created {int(row['rg_01_registry_keys_created'])} registry keys")
        if row.get('rg_02_registry_values_modified', 0) > 0:
            rg_text.append(f"modified {int(row['rg_02_registry_values_modified'])} registry values")
        if row.get('rg_03_persistence_registry_mods', 0) > 0:
            rg_text.append(f"performed {int(row['rg_03_persistence_registry_mods'])} persistence registry modifications")
        if rg_text:
            sections.append("Registry behavior: " + ", ".join(rg_text) + ".")
            
        # --- MEMORY ---
        mem_text = []
        if row.get('mem_01_remote_threads_created', 0) > 0:
            mem_text.append(f"created {int(row['mem_01_remote_threads_created'])} remote threads")
        if row.get('mem_02_cross_process_access', 0) > 0:
            mem_text.append(f"accessed {int(row['mem_02_cross_process_access'])} cross-process memory spaces")
        if mem_text:
            sections.append("Memory behavior: " + ", ".join(mem_text) + ".")
            
        # --- NETWORK ---
        nw_text = []
        if row.get('nw_01_outbound_connections_count', 0) > 0:
            nw_text.append(f"made {int(row['nw_01_outbound_connections_count'])} outbound connections")
        if nw_text:
            sections.append("Network behavior: " + ", ".join(nw_text) + ".")
            
        # --- DLL ---
        dll_text = []
        if row.get('dll_01_image_load_count', 0) > 0:
            dll_text.append(f"loaded {int(row['dll_01_image_load_count'])} DLL images")
        if dll_text:
            sections.append("DLL behavior: " + ", ".join(dll_text) + ".")
            
        if not sections:
            return "The process performed no observable malicious behavior during this window."
            
        return " ".join(sections)

    
    def predict_text(self, text):
        """
        Phase 5B Inference: Takes the pre-computed behavioral_text directly.
        Input: exact string generated by live_domain_converter.py
        Output: dict with prediction and probabilities.
        """
        if not self.is_loaded:
            return {
                "generated_text": text,
                "prediction": "UNKNOWN (Model Not Loaded)",
                "benign_probability": 0.0,
                "ransomware_probability": 0.0,
                "error": "Model training in progress or directory not found."
            }
            
        inputs = self.tokenizer(text, padding="max_length", truncation=True, max_length=128, return_tensors="pt")
        inputs = {k: v.to(self.device) for k, v in inputs.items()}
        
        with torch.no_grad():
            outputs = self.model(**inputs)
            logits = outputs.logits.cpu().numpy()[0]
            
        probs = np.exp(logits) / np.sum(np.exp(logits))
        pred_class = np.argmax(probs)
        
        return {
            "generated_text": text,
            "prediction": "Ransomware" if pred_class == 1 else "Benign",
            "benign_probability": round(float(probs[0]), 4),
            "ransomware_probability": round(float(probs[1]), 4)
        }

    def predict(self, row):
        text = self.convert_to_text(row)
        
        if not self.is_loaded:
            return {
                "generated_text": text,
                "prediction": "UNKNOWN (Model Not Loaded)",
                "benign_probability": 0.0,
                "ransomware_probability": 0.0,
                "error": "Model training in progress or directory not found."
            }
            
        # Tokenize and predict
        inputs = self.tokenizer(text, padding="max_length", truncation=True, max_length=128, return_tensors="pt")
        inputs = {k: v.to(self.device) for k, v in inputs.items()}
        
        with torch.no_grad():
            outputs = self.model(**inputs)
            logits = outputs.logits.cpu().numpy()[0]
            
        # Softmax
        probs = np.exp(logits) / np.sum(np.exp(logits))
        pred_class = np.argmax(probs)
        
        return {
            "generated_text": text,
            "prediction": "Ransomware" if pred_class == 1 else "Benign",
            "benign_probability": round(float(probs[0]), 4),
            "ransomware_probability": round(float(probs[1]), 4)
        }

def offline_test():
    print("--- Live BERT Inference Offline Test ---")
    
    csv_path = '5_mlran_dataset/Phase5A_Live_Telemetry/phase5a_benign_telemetry.csv'
    if not os.path.exists(csv_path):
        print(f"[-] Test dataset missing: {csv_path}")
        return
        
    df = pd.read_csv(csv_path)
    test_row = df.iloc[0]
    
    inference_engine = LiveBERTInference()
    
    print("\n[Input 21-Feature Vector (Sample)]")
    features_21 = [
        'fs_01_creation_count', 'fs_02_modification_count', 'fs_03_deletion_count', 'fs_04_rename_count', 
        'fs_05_unique_extensions_modified', 'fs_06_executable_files_dropped', 'pr_01_child_process_count', 
        'pr_02_suspicious_child_count', 'pr_03_process_termination_count', 'rg_01_registry_keys_created', 
        'rg_02_registry_values_modified', 'rg_03_persistence_registry_mods', 'mem_01_remote_threads_created', 
        'mem_02_cross_process_access', 'nw_01_outbound_connections_count', 'nw_02_unique_destination_ips', 
        'dll_01_image_load_count', 'dll_02_unsigned_image_load_count', 'rel_01_spawned_by_vulnerable_app', 
        'tmp_01_file_operations_per_second', 'tmp_02_registry_modifications_per_sec'
    ]
    for feat in features_21:
        if feat in test_row:
            print(f"  {feat}: {test_row[feat]}")
            
    print("\n[Running Prediction]")
    result = inference_engine.predict(test_row)
    
    print(f"\nGenerated Text: {result['generated_text']}")
    print(f"Prediction: {result['prediction']}")
    print(f"Benign Probability: {result['benign_probability']}")
    print(f"Ransomware Probability: {result['ransomware_probability']}")
    if "error" in result:
        print(f"\nNOTE: {result['error']}")

if __name__ == "__main__":
    offline_test()
