import re

with open('bert_xai.py', 'r', encoding='utf-8') as f:
    content = f.read()

new_methods = """
    def explain_text(self, text, num_features=5, num_samples=100):
        \"\"\"
        Phase 5B LIME Explanation: Takes the pre-computed behavioral_text directly.
        Input: exact string generated by live_domain_converter.py
        Output: dict with top contributing words/phrases and probabilities.
        \"\"\"
        if not self.inference_engine.is_loaded:
            return {
                "generated_text": text,
                "prediction": "UNKNOWN",
                "benign_probability": 0.0,
                "ransomware_probability": 0.0,
                "top_contributions": [],
                "error": "Model training in progress or directory not found."
            }
            
        baseline_probs = self._predict_proba([text])[0]
        pred_class = np.argmax(baseline_probs)
        
        exp = self.explainer.explain_instance(
            text, 
            self._predict_proba, 
            num_features=num_features, 
            num_samples=num_samples
        )
        
        contributions = exp.as_list(label=1)
        
        return {
            "generated_text": text,
            "prediction": "Ransomware" if pred_class == 1 else "Benign",
            "benign_probability": round(float(baseline_probs[0]), 4),
            "ransomware_probability": round(float(baseline_probs[1]), 4),
            "top_contributions": contributions,
            "disclaimer": "This represents model attribution/contribution, NOT causal proof."
        }
"""

if "def explain_text" not in content:
    content = content.replace("def explain(self, row, num_features=5, num_samples=100):", new_methods + "\n    def explain(self, row, num_features=5, num_samples=100):")

with open('bert_xai.py', 'w', encoding='utf-8') as f:
    f.write(content)
