import re

with open('live_bert_inference.py', 'r', encoding='utf-8') as f:
    content = f.read()

new_methods = """
    def predict_text(self, text):
        \"\"\"
        Phase 5B Inference: Takes the pre-computed behavioral_text directly.
        Input: exact string generated by live_domain_converter.py
        Output: dict with prediction and probabilities.
        \"\"\"
        if not self.is_loaded:
            return {
                "generated_text": text,
                "prediction": "UNKNOWN (Model Not Loaded)",
                "benign_probability": 0.0,
                "ransomware_probability": 0.0,
                "error": "Model training in progress or directory not found."
            }
            
        inputs = self.tokenizer(text, padding="max_length", truncation=True, max_length=128, return_tensors="pt")
        inputs = {k: v.to(self.device) for k, v in inputs.items()}
        
        with torch.no_grad():
            outputs = self.model(**inputs)
            logits = outputs.logits.cpu().numpy()[0]
            
        probs = np.exp(logits) / np.sum(np.exp(logits))
        pred_class = np.argmax(probs)
        
        return {
            "generated_text": text,
            "prediction": "Ransomware" if pred_class == 1 else "Benign",
            "benign_probability": round(float(probs[0]), 4),
            "ransomware_probability": round(float(probs[1]), 4)
        }
"""

if "def predict_text" not in content:
    content = content.replace("def predict(self, row):", new_methods + "\n    def predict(self, row):")

with open('live_bert_inference.py', 'w', encoding='utf-8') as f:
    f.write(content)
